<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
    </brand>
    <formFactors>Large</formFactors>
    <label>CTI AGENT</label>
    <navType>Standard</navType>
    <tab>standard-Order</tab>
    <tab>standard-Account</tab>
    <tab>Achievement_Category__c</tab>
    <tab>Achievement__c</tab>
    <tab>Tom_Admin_Guide</tab>
    <tab>Agent_Achievement__c</tab>
    <tab>Agent_Attendance__c</tab>
    <tab>Agent_Scheduling__c</tab>
    <tab>Agent_Shift__c</tab>
    <tab>standard-AppLauncher</tab>
    <tab>standard-ProcessInstanceWorkitem</tab>
    <tab>standard-Asset</tab>
    <tab>standard-Event</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Case</tab>
    <tab>standard-Feed</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Contract</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-File</tab>
    <tab>standard-Forecasting3</tab>
    <tab>standard-ForecastingLightning</tab>
    <tab>Getting_Started_With_Survey_Force</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>Help_Center_Article__c</tab>
    <tab>Holiday_Calendar__c</tab>
    <tab>standard-home</tab>
    <tab>standard-Lead</tab>
    <tab>Learning</tab>
    <tab>SubTabAchievements</tab>
    <tab>Learning_Assignment__c</tab>
    <tab>Learning_Category__c</tab>
    <tab>Learning__c</tab>
    <tab>dlrs__LookupRollupCalculateJob__c</tab>
    <tab>dlrs__LookupRollupSummary__c</tab>
    <tab>dlrs__LookupRollupSummaryLog__c</tab>
    <tab>dlrs__LookupRollupSummaryScheduleItems__c</tab>
    <tab>dlrs__ManageLookupRollupSummaries</tab>
    <tab>Multiple_Agent_Scheduling</tab>
    <tab>MyTimeOffBalance</tab>
    <tab>My_Training</tab>
    <tab>standard-Opportunity</tab>
    <tab>Pay_Cycle__c</tab>
    <tab>Payroll_System__c</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>PKB_2_Settings</tab>
    <tab>PKB_Article_Feedback_Deflection__c</tab>
    <tab>PKB_Featured__c</tab>
    <tab>standard-Pricebook2</tab>
    <tab>standard-Product2</tab>
    <tab>QA_Agent_Answer__c</tab>
    <tab>QA_Question__c</tab>
    <tab>Quiz__c</tab>
    <tab>standard-report</tab>
    <tab>Response__c</tab>
    <tab>scss__SCS_SocialLookup_Setup</tab>
    <tab>standard-SocialPost</tab>
    <tab>Start_Here</tab>
    <tab>Survey_Question__c</tab>
    <tab>Survey__c</tab>
    <tab>SurveyTaker__c</tab>
    <tab>standard-Task</tab>
    <tab>Team_Calendar</tab>
    <tab>Time_Off_Info__c</tab>
    <tab>Tom_Setup</tab>
    <tab>Time_Off_Request__c</tab>
    <tab>TML_Answer_Sequence__c</tab>
    <tab>TML_Question__c</tab>
    <tab>Training_Plan__c</tab>
    <tab>Training_Track__c</tab>
    <tab>Tom_User_Guide</tab>
    <tab>dlrs__Welcome</tab>
    <tab>standard-WorkOrder</tab>
    <tab>Zendesk__Zendesk</tab>
    <tab>Zendesk__Zendesk_Agent_Details__c</tab>
    <tab>Zendesk__Zendesk_Bulk_Sync</tab>
    <tab>Zendesk__IntegrationLogs</tab>
    <tab>Zendesk__Zendesk_Ticket__c</tab>
    <uiType>Lightning</uiType>
    <utilityBar>CTI_AGENT_UtilityBar</utilityBar>
</CustomApplication>
