<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <navType>Console</navType>
    <tab>standard-home</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Task</tab>
    <tab>standard-Event</tab>
    <tab>standard-ContentNote</tab>
    <tab>standard-report</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-File</tab>
    <tab>Agent_Scheduling__c</tab>
    <tab>Agent_Attendance__c</tab>
    <tab>Agent_Shift__c</tab>
    <tab>QA_Question__c</tab>
    <tab>Agent_Achievement__c</tab>
    <tab>Multiple_Agent_Scheduling</tab>
    <tab>QA_Agent_Answer__c</tab>
    <tab>Help_Center_Article__c</tab>
    <uiType>Lightning</uiType>
    <utilityBar>LightningSalesConsole_UtilityBar</utilityBar>
</CustomApplication>
